### PR TITLE
MELPA patch

### PR DESCRIPTION
**Pull request by riscy**
Handful of fixes re: https://github.com/melpa/melpa/pull/6742

### CODE REVIEW

**Comment by riscy** [comment]
@googlebot I signed it!

**Comment by phst** [comment]
These changes look fine, but could you please explain the reasoning behind them a bit?

**Comment by riscy** [comment]
Sure -- a user is hoping to get the package added to MELPA.  We've even determined that this should really be the official bazel-mode package, complete with the blessing of the author of MELPA's current bazel-mode.

MELPA needs some [additional metadata in the header](https://github.com/melpa/melpa/pull/6742) and I've gone ahead and removed the word "Emacs" when it felt redundant  -- but drop that commit if you like.

MELPA also recommends [some common lints](https://github.com/purcell/package-lint), the only even minorly significant one in this repo is to prefer "bazel" as the defgroup instead of "bazel-mode" (since your prefix is effectively "bazel-" anyway).

**Comment by phst** [comment]
Thanks! Would you mind splitting this up into 3 PRs, and also add the explanation to the commit messages? IIUC this repo only allows squash merges, so the individual commits would be lost after the merge.

**Pull request closed without merging**
